version: 0.2

env:
  variables:
    ENV: "prod"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$ENV
      - docker pull $IMAGE_URI || true
  build:
    commands:
      - echo Build started for '$ENV' on `date`
      - echo Building the Docker image '$IMAGE_REPO_NAME:$ENV'
      - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
      - docker build --cache-from $IMAGE_URI -t $IMAGE_REPO_NAME:$ENV .
      - echo Tagging image as '$IMAGE_URI'
      - docker tag $IMAGE_REPO_NAME:$ENV $IMAGE_URI      
  post_build:
    commands:
      - echo Build completed for '$ENV' on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_URI
      - echo Writing image definitions file - $IMAGE_REPO_NAME-$ENV pointing to $IMAGE_URI
      - printf '[{"name":"%s-%s","imageUri":"%s"}]' $IMAGE_REPO_NAME $ENV $IMAGE_URI > imagedefinitions.json
artifacts:
  files: imagedefinitions.json